// ============================================================
// mdmeta — Core Type Definitions
// ============================================================

/**
 * Raw heading information extracted from the markdown-it lexer.
 * Intermediate representation before full section metadata is computed.
 */
export interface HeadingInfo {
  /** Raw heading text content */
  text: string;
  /** Heading depth (1–6) */
  level: number;
  /** 1-indexed line number where the heading starts */
  line: number;
}

/**
 * A single section in the document's structural index.
 * Stored in the `.meta` file as part of the `sections` array.
 */
export interface SectionMeta {
  /** Section identifier, generated by the active ID strategy */
  id: string;
  /** Raw heading text (e.g. "Install Steps"). Empty string for preamble. */
  heading: string;
  /** Heading depth (1–6). 0 for preamble (content before first heading). */
  level: number;
  /** 1-indexed line number where this section starts (inclusive) */
  line_start: number;
  /** 1-indexed line number where this section ends (inclusive) */
  line_end: number;
  /** Character count of this section's own content (excluding subsections) */
  char_count: number;
  /** Character count including all nested subsections */
  total_char_count: number;
  /** Number of direct child sections */
  subsection_count: number;
  /** IDs of direct child sections */
  subsections: string[];
  /** ID of parent section, or null for top-level sections */
  parent: string | null;
  /** SHA-256 hash of this section's own content (excluding subsections) */
  checksum: string;
  /** ISO 8601 timestamp of when this section's content last changed */
  last_modified: string;
}

/**
 * The complete `.meta` file structure.
 * This is the JSON schema written to `<filename>.md.meta`.
 */
export interface DocumentMeta {
  /** Schema version for forward compatibility */
  version: number;
  /** Relative path to the source `.md` file */
  source: string;
  /** SHA-256 hash of the entire `.md` file content */
  checksum: string;
  /** ISO 8601 timestamp of when this metadata was last generated */
  last_indexed: string;
  /** Which ID strategy was used to generate section IDs */
  id_strategy: string;
  /** Flat array of sections in document order */
  sections: SectionMeta[];
}

/**
 * Tree node for the outline view returned by `getOutline()`.
 * Converts the flat `sections` array into a nested hierarchy.
 */
export interface OutlineNode {
  /** Section identifier */
  id: string;
  /** Raw heading text */
  heading: string;
  /** Heading depth (1–6, or 0 for preamble) */
  level: number;
  /** Character count of own content */
  char_count: number;
  /** Character count including all subsections */
  total_char_count: number;
  /** When this section's content last changed */
  last_modified: string;
  /** Nested child outline nodes */
  children: OutlineNode[];
}

/** Valid ID generation strategy names */
export type IdStrategyName = 'slug' | 'path' | 'hash';

/** Valid indexing strategy names */
export type IndexStrategyName = 'eager' | 'lazy' | 'hybrid';

/**
 * Configuration file schema (`mdmeta.config.json`).
 * Controls which directories are indexed, how IDs are generated,
 * and when files are parsed.
 */
export interface MdMetaConfig {
  /** Directories to index. Relative to config file location. */
  roots: string[];
  /** Glob patterns to exclude from indexing */
  ignore: string[];
  /** How section IDs are generated */
  idStrategy: IdStrategyName;
  /** When to parse and generate `.meta` files */
  indexStrategy: IndexStrategyName;
}

/**
 * Function signature for an ID generation strategy.
 * Must produce deterministic, stable IDs for the same input.
 */
export type IdStrategyFn = (
  heading: string,
  level: number,
  parentId: string | null,
  index: number,
) => string;
